//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityPowerService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CityPowerService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListMethod.
        /// </summary>
        internal static string K2_Municiplalities_List_Method_Description {
            get {
                return ResourceManager.GetString("K2_Municiplalities_List_Method_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMuniciplalities.
        /// </summary>
        internal static string K2_Municiplalities_List_Method_DisplayName {
            get {
                return ResourceManager.GetString("K2_Municiplalities_List_Method_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMuniciplalities.
        /// </summary>
        internal static string K2_Municiplalities_List_Method_Name {
            get {
                return ResourceManager.GetString("K2_Municiplalities_List_Method_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a list of Municiplalities based on Province.
        /// </summary>
        internal static string K2_Municiplalities_ServiceObject_Description {
            get {
                return ResourceManager.GetString("K2_Municiplalities_ServiceObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMuniciplalities.
        /// </summary>
        internal static string K2_Municiplalities_ServiceObject_DisplayName {
            get {
                return ResourceManager.GetString("K2_Municiplalities_ServiceObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMuniciplalities.
        /// </summary>
        internal static string K2_Municiplalities_ServiceObject_Name {
            get {
                return ResourceManager.GetString("K2_Municiplalities_ServiceObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityPowerService.
        /// </summary>
        internal static string K2_Name {
            get {
                return ResourceManager.GetString("K2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListMethod.
        /// </summary>
        internal static string K2_Province_List_Method_Description {
            get {
                return ResourceManager.GetString("K2_Province_List_Method_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProvince.
        /// </summary>
        internal static string K2_Province_List_Method_DisplayName {
            get {
                return ResourceManager.GetString("K2_Province_List_Method_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProvince.
        /// </summary>
        internal static string K2_Province_List_Method_Name {
            get {
                return ResourceManager.GetString("K2_Province_List_Method_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method to return the province ID.
        /// </summary>
        internal static string K2_Province_ServiceObject_Description {
            get {
                return ResourceManager.GetString("K2_Province_ServiceObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProvince.
        /// </summary>
        internal static string K2_Province_ServiceObject_DisplayName {
            get {
                return ResourceManager.GetString("K2_Province_ServiceObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProvince.
        /// </summary>
        internal static string K2_Province_ServiceObject_Name {
            get {
                return ResourceManager.GetString("K2_Province_ServiceObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method to get the current loadshedding stage.
        /// </summary>
        internal static string K2_Search_List_Method_Description {
            get {
                return ResourceManager.GetString("K2_Search_List_Method_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStage.
        /// </summary>
        internal static string K2_Search_List_Method_DisplayName {
            get {
                return ResourceManager.GetString("K2_Search_List_Method_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStage.
        /// </summary>
        internal static string K2_Search_List_Method_Name {
            get {
                return ResourceManager.GetString("K2_Search_List_Method_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is my first Custom ServiceBroker Object using a Default Template.
        /// </summary>
        internal static string K2_Search_ServiceObject_Description {
            get {
                return ResourceManager.GetString("K2_Search_ServiceObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStage.
        /// </summary>
        internal static string K2_Search_ServiceObject_DisplayName {
            get {
                return ResourceManager.GetString("K2_Search_ServiceObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStage.
        /// </summary>
        internal static string K2_Search_ServiceObject_Name {
            get {
                return ResourceManager.GetString("K2_Search_ServiceObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This currently does nothing, but can be extended to business needs.
        /// </summary>
        internal static string K2_Service_Description {
            get {
                return ResourceManager.GetString("K2_Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Power Service.
        /// </summary>
        internal static string K2_Service_DisplayName {
            get {
                return ResourceManager.GetString("K2_Service_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityPowerService.
        /// </summary>
        internal static string K2_Service_Name {
            get {
                return ResourceManager.GetString("K2_Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method to get a list of all suburbs in City Power.
        /// </summary>
        internal static string K2_Suburb_List_Method_Description {
            get {
                return ResourceManager.GetString("K2_Suburb_List_Method_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSuburb.
        /// </summary>
        internal static string K2_Suburb_List_Method_DisplayName {
            get {
                return ResourceManager.GetString("K2_Suburb_List_Method_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSuburb.
        /// </summary>
        internal static string K2_Suburb_List_Method_Name {
            get {
                return ResourceManager.GetString("K2_Suburb_List_Method_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is my first Custom ServiceBroker Object using a Default Template.
        /// </summary>
        internal static string K2_Suburb_ServiceObject_Description {
            get {
                return ResourceManager.GetString("K2_Suburb_ServiceObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSuburb.
        /// </summary>
        internal static string K2_Suburb_ServiceObject_DisplayName {
            get {
                return ResourceManager.GetString("K2_Suburb_ServiceObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSuburb.
        /// </summary>
        internal static string K2_Suburb_ServiceObject_Name {
            get {
                return ResourceManager.GetString("K2_Suburb_ServiceObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListMethod.
        /// </summary>
        internal static string K2_Times_List_Method_Description {
            get {
                return ResourceManager.GetString("K2_Times_List_Method_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLoadsheddingTimes.
        /// </summary>
        internal static string K2_Times_List_Method_DisplayName {
            get {
                return ResourceManager.GetString("K2_Times_List_Method_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLoadsheddingTimes.
        /// </summary>
        internal static string K2_Times_List_Method_Name {
            get {
                return ResourceManager.GetString("K2_Times_List_Method_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method to get the start and end times of loadshedding.
        /// </summary>
        internal static string K2_Times_ServiceObject_Description {
            get {
                return ResourceManager.GetString("K2_Times_ServiceObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLoadsheddingTimes.
        /// </summary>
        internal static string K2_Times_ServiceObject_DisplayName {
            get {
                return ResourceManager.GetString("K2_Times_ServiceObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLoadsheddingTimes.
        /// </summary>
        internal static string K2_Times_ServiceObject_Name {
            get {
                return ResourceManager.GetString("K2_Times_ServiceObject_Name", resourceCulture);
            }
        }
    }
}
